version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: devhire-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepostgres123
      POSTGRES_DB: devhire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: devhire-api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:securepostgres123@db:5432/devhire
      SECRET_KEY: devhire-super-secure-jwt-secret-key-change-in-prod
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    volumes:
      - .:/app

volumes:
  pgdata: