"""add application unique constraint

Revision ID: 7d1ed134b01c
Revises: 0ae675de5445
Create Date: 2026-06-01 19:45:20.091003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1ed134b01c'
down_revision: Union[str, Sequence[str], None] = '0ae675de5445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_candidate_job', 'applications', ['candidate_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candidate_job', 'applications', type_='unique')
    # ### end Alembic commands ###
